name: GitHub actions event dispatcher
on:
  push:
  workflow_dispatch:
    inputs:
      source:
        description: Build event to be dispatched
        required: false
jobs:
  dispatch:
    name: Dispatch GitHub actions events.
    runs-on: ubuntu-latest

    steps:
    - name: Create repository_dispatch event
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.CI_ACCESSTOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'ibissource',
            repo: 'frank-runner',
            workflow_id: 'test-frank-runner.yml',
            ref: 'master'
          })
